import Head from 'next/head'
import {motion as m} from "framer-motion";

export default function Home() {
    return (
        <m.div
            initial={{opacity: 0}}
            animate={{opacity: 1}}
            transition={{duration: 0.75, ease: "easeOut"}}
            exit={{opacity: 0}}
            className={"text-gray-900 absolute top-0 left-0 w-full h-full bg-orange-100"}
        >
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <div className="my-96 p-1">
                    <h1 className={"text-6xl text-center lg:text-9xl"}>
                        Happy Pickle
                    </h1>
                </div>
                <div className="flex justify-between">
                    <div>
                        <h2>Design</h2>
                        <h2>Company</h2>
                        <h2>2022</h2>
                    </div>
                    <div>
                        <h2>This pickle will make you smile</h2>
                        <h2>Scottish designs to make you happy</h2>
                        <h2>Click contact for cool transition</h2>
                    </div>
                </div>

            </main>

            <footer>

            </footer>
        </m.div>
    )
}
